name: CI Workflow
on:
  push:
    branches:
      - main
      - CI_branch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 task_Andrey_Simkin_prime.py
      - run: echo OK
